import React from 'react';
import Head from 'next/head';
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../src/components/sharedstyles';
import Cards from '../src/components/cards';
import Layout from '../src/layouts/Layout';
import CardWrapper from '../src/components/CardWrapper';
import dbConnect from '../utils/mongo/dbConnect';
import Product from '../utils/mongo/Product';

export default function Home({ products }) {
  console.log('products', products);
  return (
    // <Container>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name='description' content='Generated by create next app' />
    //     <link rel='icon' href='/favicon.ico' />
    //   </Head>
    //   <Main>
    //     <Title>
    //       Welcome to <a href='https://nextjs.org'>Next.js!</a>
    //     </Title>

    //     <Description>
    //       Get started by editing
    //       <CodeTag>pages/index.tsx</CodeTag>
    //     </Description>

    //     <Cards />
    //   </Main>
    // </Container>
    <Layout title='Home' description='Seller-App Home page'>
      <CardWrapper />
    </Layout>
  );
}

export async function getServerSideProps() {
  await dbConnect();

  /* find all the data in our database */
  const result = await Product.find({});
  const products = result.map((doc) => {
    const product = doc.toObject();
    product._id = product._id.toString();
    return product;
  });

  return { props: { products: products } };
}
